[tool.black]
line-length = 100

[tool.isort]
include_trailing_comma = true
line_length = 100
multi_line_output = 3
known_third_party =["matplotlib", "networkx", "numpy", "pandas", "tools", "ts2vg", "vg_class"]
